name: Commit with no details

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  create-and-commit-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Commit file with no details
        run: bash ./commit-no-author.sh
